export { default as Home } from './home'
export { default as GitHub } from './github'
export { default as Twitter } from './twitter'
export { default as Linkedin } from './linkedin'
export { default as Mail } from './mail'
